Feature/stageapi
CodeParty2021/code_party_back pull request #22
Opened 2022-01-25 19:01 UTC by TAKUMI-TAKAMATU

# やったこと
- stageapiの方にfilter.pyを追加した
- test_apiにfilterのorder_by用の動作確認用のテストtest_getfiltered_examples_with_a_fieldを追加
- test_apiにworldのidによるフィルタリングのテストtest_getfiltered_examples_world_idを追加
- StageAPIのモデルをwikiにあった形に変更(nameの削除、ruleをobjectiveに変更、movie_urlの変更)
- モデルに合わせた形にテストを変更

2022-01-26 16:32 UTC, iikyara requested changes
修正お願いします！

2022-01-26 17:33 UTC, TAKUMI-TAKAMATU commented on stage_api/migrations/0001_initial.py
> +                ("objective", models.CharField(max_length=300)),
DB関連でエラーが出たときに、自分で変えてた記憶があったので、手動で元に戻しました

2022-01-26 17:33 UTC, TAKUMI-TAKAMATU commented on stage_api/models.py
> +    w_id = models.ForeignKey(World, on_delete=models.CASCADE)
修正しました

2022-01-26 17:35 UTC, TAKUMI-TAKAMATU commented on stage_api/tests/test_api.py
> +from tkinter import W
削除しました

2022-01-26 17:36 UTC, TAKUMI-TAKAMATU commented on stage_api/tests/test_api.py
> +            {"stageIndex": 10,
インデントの修正をしました

2022-01-26 17:36 UTC, TAKUMI-TAKAMATU commented on stage_api/tests/test_api.py
> +            {"stageIndex": 1,
修正しました

2022-01-26 17:37 UTC, TAKUMI-TAKAMATU commented on stage_api/tests/test_api.py
> +                {"id": 2,
修正しました

2022-01-26 17:37 UTC, TAKUMI-TAKAMATU commented on stage_api/models.py
>      stage_index = models.IntegerField()
indexにしました

2022-01-27 00:07 UTC, iikyara requested changes
修正お疲れ様です！
stage_indexが残っている部分があるようなので修正お願いします！
その他何点かコメントしたのでお願いします！

2022-01-27 00:07 UTC, iikyara commented on stage_api/tests/test_api.py
> +
すみません！前回確認漏れしてたのですが，indexでの検索があるので，そちらのテストも記述してほしいです！
worldフィールドでの検索をindexフィールドでの検索に変えたテストをもう一つ作成お願いします！

2022-01-27 00:07 UTC, iikyara commented on stage_api/tests/test_api.py
> +                {"id": 2,
```
{"id": 2,
```
を改行して
```
{
　"id": 2,
　"index": 1,
　...
}
```
みたいな感じにするイメージだったんだけどblackで修正されちゃう感じでしょうか？
直せそうだったらお願いします！

2022-01-28 02:30 UTC, iikyara approved these changes
完璧です！色々修正していただきありがとうございました！
お疲れ様でした！

2022-01-28 03:51 UTC, merged