UserRetrieveViewを作成
CodeParty2021/code_party_back pull request #23
Opened 2022-02-09 11:11 UTC by iikyara

追加
- UserRetrieveView

修正
- テストコード
- 必要ないprint文を削除
- 仕様書に従ってis_created→createdに変更

2022-02-09 14:22 UTC, iikyara commented
追記
- #19 も修正しました．テストが正常に動くようになっております．

2022-02-21 06:33 UTC, TAKUMI-TAKAMATU commented on users/test/test_api_local.py
>          # レスポンスのステータスコードをチェック
テストをローカルで実行したところエラーが出ています。
self.assertEquals(response.status_code, 200)
AssertionError: 403 != 200

もしsettingファイルなどに権限など追加したものがあれば、追加されていないのかもしれないです。

2022-02-23 00:07 UTC, iikyara commented on users/test/test_api_local.py
>          # レスポンスのステータスコードをチェック
これ以前の会議で話してた，古いトークンをテストケースに入れてるのが問題なんだよね．現状解決策はありません...
一旦このテストケースは消して，ローカルで簡易テストできるようなスクリプトだけ用意します．

2022-02-23 02:17 UTC, iikyara commented on users/test/test_api_local.py
>          # レスポンスのステータスコードをチェック
テストをコマンド形式で実行できるように変更しました．自動テストは出来ませんが，不具合の時にコマンドを実行して手軽に調べることが出来ます．以下のコマンドからテストを実行できます．README.mdにも追記したので参考にしてください．

```
python manage.py auth_test
```

2022-02-23 05:48 UTC, TAKUMI-TAKAMATU requested changes

2022-02-23 05:48 UTC, TAKUMI-TAKAMATU commented on users/test/test_user_retrieve_view.py
> +class StageAPITests(TestCase):
UserAPITests ?

2022-02-23 06:03 UTC, iikyara commented on users/test/test_user_retrieve_view.py
> +class StageAPITests(TestCase):
修正しました！

2022-02-23 07:06 UTC, TAKUMI-TAKAMATU approved these changes

2022-02-23 07:08 UTC, TAKUMI-TAKAMATU reviewed
大丈夫だと思います！お疲れ様でした！

2022-02-23 07:09 UTC, merged